import EventCard from "@/components/EventCard";
import { supabase } from "@/utils/supabaseClient";
import Head from "next/head";
import Image from "next/image";

import data from "../public/data.json";

export default function Events({ events }: { events: any }): JSX.Element {
  return (
    <>
      <Head>
        <title>{data["title"] + " Events"  }</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="h-full w-full 
       bg-gradient-to-tl from-fuchsia-950 to-black z-10 relative"
      >
        <div className="flex flex-col justify-start items-left ">
          <h1 className="text-5xl text-left font-normal text-white px-10 pt-10">
            Events.
          </h1>
          <span className="text-2xl text-left font-thin text-white px-10 ">
            Participate and emerge victorious in these eyegrabbing events.
          </span>
        </div>
        <div className="flex flex-row flex-wrap justify-center items-center">
          {events.map((event: any) => (
            <EventCard key={event.id} eventData={event} />
          ))}
        </div>
        <Image 
      src="https://i.imgur.com/G42sxIN.png"
      alt="Background"
      width={700}
      height={700}
      className="fixed md:top-36 md:right-28 opacity-25 top-24 -right-16"
      style={{
        zIndex: 0,
      }}
      />
      </main>
     
    </>
  );
}

export async function getServerSideProps() {
  let { data } = await supabase.from("events").select("*");

  return {
    props: {
      events: data,
    },
  };
}
