import Head from "next/head";
import localFont from '@next/font/local';
import Hero from "./../components/hero"
import data from "../public/data.json";

// export async function getServerSideProps() {
//   // Fetch data from external API
//   const res = await fetch(`public/data.json`);
//   const data = await res.json();

//   // Pass data to the page via props
//   return { props: { data } };
// }

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>{data["title"]}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Hero/>
      </main>
    </>
  );
}
