import Head from "next/head";
import localFont from "@next/font/local";
import Hero from "./../components/hero";
import data from "../public/data.json";
import NavBar from "@/components/navbar";
import ContactUs from "@/components/ContactUs";
import Footer from "@/components/Footer";
import { Data } from "./../utils/data/Data";
import { Card } from "flowbite-react";
import { supabase } from "@/utils/supabaseClient";
import { getEvents } from "@/utils/getEvents";

// export async function getServerSideProps() {
//   // Fetch data from external API
//   const res = await fetch(`public/data.json`);
//   const data = await res.json();

//   // Pass data to the page via props
//   return { props: { data } };
// }

// interface Item {
//   name: string;
//   details: string;
//   poster_image?: string;
// }

export default function Home({ events }: { events: any }): JSX.Element {
  console.log(events);

  return (
    <>
      <Head>
        <title>{data["title"]}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="bg-gradient-to-tl from-fuchsia-950 to-black pt-32">
        <Hero />
        <div className="event-card">
          {/* {events.map((item: any, index: number) => (
            <Card key={index} eventData={item} />
          ))} */}
        </div>
        <ContactUs />
        <Footer />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  let data;

  try {
    data = await getEvents("name, details, poster_image,rules_regulations");
  } catch (err) {
    console.log(err);
  }

  return {
    props: {
      events: data,
    },
  };
}
