import { signupWithEmail } from "@/utils/signup";
import Head from "next/head";
import { useState } from "react";

export default function Signup() {
  const [error, setError] = useState("");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form
          onSubmit={() => {
            signupWithEmail({
              //
              email: "",
              password: "",
            });
          }}
        >
          <input name="email" type="email" placeholder="Enter Email"></input>
          <input
            name="password"
            type="password"
            placeholder="Enter Password"
          ></input>
          <input
            name="password-condfirm"
            type="password"
            placeholder="Confirm password"
          ></input>
          <button>Sign Up!</button>
        </form>
      </main>
    </>
  );
}
